-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Fun.

module Fun.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = Prog [Def] Main
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Main = DMain Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Def = DDef Ident [Ident] Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr = Var Ident | App Expr Expr | Lambda Ident Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

